### ISSUE TITLE
PHP Catchable Fatal Error with rnbase

### ISSUE THREAD

**Issue by ThePinkOne** [DMKEBUSINESSGMBH/typo3-mksearch#36] opened 2017-09-21 13:45 UTC
I'm testing mksearch with solr and Typo3 7.6.22 .
Everything worked fine, I added an index, indexer composites and configuration. But then I got an error/mayday _"Unknown Operator for comparation defined: OP_EQ_INT"_ . Here the full output:

_Core: Exception handler (WEB): Uncaught TYPO3 Exception: Unknown Operator for comparation defined: OP_EQ_INT | tx_rnbase_util_Exception thrown in file /var(...)/websitename/vendor/typo3/cms/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 4555. Requested URL: http://websitename/typo3/index.php?M=web_MksearchM1&moduleToken=94fb524cc396e017d3fd249342dbe71b6beb057e&id=333_ 

When I read rnbase I thought I could try to fix this issue by having a look in the rn_base configuration. I changed nothing but now I can't even open mksearch UI in the backend. I only get this error

_Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1: PHP Catchable Fatal Error: Argument 2 passed to Tx_Rnbase_Backend_Utility_Icons::getSpriteIconForRecord() must be of the type array, null given, called in /var/(...)/websitename/web/typo3conf/ext/mksearch/mod1/util/class.tx_mksearch_mod1_util_Misc.php on line 57 and defined in /var/(...)/websitename/web/typo3conf/ext/rn_base/Classes/Backend/Utility/Icons.php line 80 | TYPO3\CMS\Core\Error\Exception thrown in file /var/(...)/websitename/vendor/typo3/cms/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 111. Requested URL: http://websitename/typo3/index.php?M=web_MksearchM1&moduleToken=94fb524cc396e017d3fd249342dbe71b6beb057e&id=10&_ 

Any ideas what's going on?

**Comment by hannesbochmann** [comment] 2017-09-21 14:26
Did you try to use the last available releases of rn_base (v1.4.5) and mksearch (v3.0.8) from github.

**Comment by ThePinkOne** [comment] 2017-09-21 15:26
No, we use composer mode so I just got rn_base 1.4.0 and mksearch 3.0.0 .
I'll try the new releases from github and report later.

**Comment by ThePinkOne** [comment] 2017-09-25 08:22
Okay, everything is up to date now but nothing changed. I still get this error. I've deleted the sysfolder, added a new one, deleted my cache...

**Comment by hannesbochmann** [comment] 2017-09-25 10:23
Seems like an issue due to autoloading. I haven't got a TYPO3 environment without composer right now, so I can't reproduce this error. 
P.S. You are not the only one having this problem when composer is not used.

**Comment by ThePinkOne** [comment] 2017-09-25 10:31
You've got me wrong:
I am using composer, I just had to add github to get the newest releases of mksearch and rn_base. I get them from typo3-ter before.

**Comment by hannesbochmann** [comment] 2017-09-25 10:32
Okay, I will check that.

**Comment by hannesbochmann** [comment] 2017-09-26 12:41
With the current master of rn_base everything should be fixed. Could you please check that?

**Closed** 2017-09-26 12:40 UTC

**Comment by ThePinkOne** [comment] 2017-09-26 12:55
Thank you. I got this error

  _| Core: Exception handler (WEB): Uncaught TYPO3 Exception: SQL  QUERY IS NOT VALID<br/><b>You have an error in your SQL  syntax; check the manual that corresponds to your MariaDB server version  for the right syntax to use near 'OP_EQ_INT 335  AND  tx_mksearch_indices.deleted=0 AND tx_mksearch_indices.hidden=' at line  1</b><br />SELECT tx_mksearch_indices.* FROM  tx_mksearch_indices WHERE 1=1 AND tx_mksearch_indices.pid OP_EQ_INT 335   AND tx_mksearch_indices.deleted=0 AND tx_mksearch_indices.hidden=0 \|  tx_rnbase_util_Exception thrown in file  /var/www/webseitenname/vendor/typo3/cms/typo3/sysext/core/Classes/Utility/GeneralUtility.php  in line 4555. Requested URL:  http://webseitenname/typo3/index.php?M=web_MksearchM1&moduleToken=e154c9d15796004421cdcffe3d70fa55cb7f328e&id=335
-- | --_

Then I deleted and re-installed mksearch and now it seems to work. I'll open an new issue if I get the error again (hopefully not ;) ) . Thanks so far!!
